# Generated by Django 6.0.2 on 2026-06-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_date', models.DateField(unique=True)),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField()),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('day_name', models.CharField(max_length=20)),
                ('month_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Dimension date',
                'verbose_name_plural': 'Dimensions dates',
                'db_table': 'dw_dim_date',
                'ordering': ['full_date'],
            },
        ),
        migrations.CreateModel(
            name='DimWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_website_id', models.PositiveBigIntegerField(help_text='Identifiant du site dans la table opérationnelle Website', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ga4_property_id', models.CharField(blank=True, default='', max_length=50)),
                ('gsc_site_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dimension site',
                'verbose_name_plural': 'Dimensions sites',
                'db_table': 'dw_dim_website',
            },
        ),
        migrations.CreateModel(
            name='DimPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.TextField()),
                ('full_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='datawarehouse.dimwebsite')),
            ],
            options={
                'verbose_name': 'Dimension page',
                'verbose_name_plural': 'Dimensions pages',
                'db_table': 'dw_dim_page',
                'constraints': [models.UniqueConstraint(fields=('website', 'page_path'), name='dw_unique_page_per_website')],
            },
        ),
    ]
