# Generated by Django 6.0.2 on 2026-06-10 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimpage',
            options={'ordering': ['website', 'page_path'], 'verbose_name': 'Dimension page', 'verbose_name_plural': 'Dimensions pages'},
        ),
        migrations.AlterModelOptions(
            name='dimwebsite',
            options={'ordering': ['name'], 'verbose_name': 'Dimension site', 'verbose_name_plural': 'Dimensions sites'},
        ),
        migrations.CreateModel(
            name='FactGAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_count', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('event_count_per_user', models.FloatField(default=0.0)),
                ('total_revenue', models.FloatField(default=0.0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ga_event_facts', to='datawarehouse.dimdate')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ga_event_facts', to='datawarehouse.dimpage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ga_event_facts', to='datawarehouse.dimwebsite')),
            ],
            options={
                'verbose_name': 'Fait événement GA4',
                'verbose_name_plural': 'Faits événements GA4',
                'db_table': 'dw_fact_ga_events',
                'ordering': ['date__full_date', 'event_name'],
                'constraints': [models.UniqueConstraint(fields=('website', 'date', 'page', 'event_name'), name='dw_unique_ga_event_grain')],
            },
        ),
        migrations.CreateModel(
            name='FactGAMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_users', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('engaged_sessions', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('average_session_duration', models.FloatField(default=0.0)),
                ('screen_page_views_per_user', models.FloatField(default=0.0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ga_metrics_facts', to='datawarehouse.dimdate')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ga_metrics_facts', to='datawarehouse.dimpage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ga_metrics_facts', to='datawarehouse.dimwebsite')),
            ],
            options={
                'verbose_name': 'Fait métriques GA4',
                'verbose_name_plural': 'Faits métriques GA4',
                'db_table': 'dw_fact_ga_metrics',
                'ordering': ['date__full_date'],
                'constraints': [models.UniqueConstraint(fields=('website', 'date', 'page'), name='dw_unique_ga_metrics_grain')],
            },
        ),
        migrations.CreateModel(
            name='FactGSCMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, default='')),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gsc_metrics_facts', to='datawarehouse.dimdate')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gsc_metrics_facts', to='datawarehouse.dimpage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gsc_metrics_facts', to='datawarehouse.dimwebsite')),
            ],
            options={
                'verbose_name': 'Fait métriques GSC',
                'verbose_name_plural': 'Faits métriques GSC',
                'db_table': 'dw_fact_gsc_metrics',
                'ordering': ['date__full_date'],
                'constraints': [models.UniqueConstraint(fields=('website', 'date', 'page', 'query'), name='dw_unique_gsc_metrics_grain')],
            },
        ),
    ]
