# Generated by Django 6.0.2 on 2026-06-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouse', '0002_alter_dimpage_options_alter_dimwebsite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factgaevent',
            options={'ordering': ['date_id', 'event_name'], 'verbose_name': 'Fait événement GA4', 'verbose_name_plural': 'Faits événements GA4'},
        ),
        migrations.AlterModelOptions(
            name='factgametrics',
            options={'ordering': ['date_id'], 'verbose_name': 'Fait métriques GA4', 'verbose_name_plural': 'Faits métriques GA4'},
        ),
        migrations.AlterModelOptions(
            name='factgscmetrics',
            options={'ordering': ['date_id'], 'verbose_name': 'Fait métriques GSC', 'verbose_name_plural': 'Faits métriques GSC'},
        ),
    ]
