# Generated by Django 6.0.2 on 2026-03-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ga4_property_id', models.CharField(blank=True, max_length=50, null=True)),
                ('gsc_site_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'website',
            },
        ),
        migrations.CreateModel(
            name='GSCMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.website')),
            ],
            options={
                'db_table': 'gsc_metrics',
                'unique_together': {('website', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GAMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_users', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.website')),
            ],
            options={
                'db_table': 'ga_metrics',
                'unique_together': {('website', 'date')},
            },
        ),
    ]
