# Generated by Django 6.0.2 on 2026-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametrics',
            name='page_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gscmetrics',
            name='page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
