# Generated by Django 6.0.2 on 2026-03-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0002_gametrics_page_path_gscmetrics_page'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gametrics',
            unique_together={('website', 'date', 'page_path')},
        ),
        migrations.AlterUniqueTogether(
            name='gscmetrics',
            unique_together={('website', 'date', 'page')},
        ),
    ]
