# Generated by Django 6.0.2 on 2026-04-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0003_alter_gametrics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametrics',
            name='average_session_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gametrics',
            name='engaged_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametrics',
            name='engagement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gametrics',
            name='screen_page_views_per_user',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gametrics',
            name='vent_count',
            field=models.IntegerField(default=0),
        ),
    ]
