# Generated by Django 6.0.2 on 2026-04-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0004_gametrics_average_session_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametrics',
            old_name='vent_count',
            new_name='event_count',
        ),
    ]
