# Generated by Django 6.0.2 on 2026-04-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0005_rename_vent_count_gametrics_event_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametrics',
            name='event_count',
        ),
    ]
