# Generated by Django 6.0.2 on 2026-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0006_remove_gametrics_event_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gscmetrics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gscmetrics',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gscmetrics',
            unique_together={('website', 'date', 'page', 'query')},
        ),
    ]
