# Generated by Django 6.0.2 on 2026-04-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0007_alter_gscmetrics_unique_together_gscmetrics_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_path', models.TextField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_count', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('event_count_per_user', models.FloatField(default=0.0)),
                ('total_revenue', models.FloatField(default=0.0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.website')),
            ],
            options={
                'db_table': 'ga_events',
                'unique_together': {('website', 'date', 'page_path', 'event_name')},
            },
        ),
    ]
