# Generated by Django 6.0.2 on 2026-04-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0008_gaevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('title_length', models.IntegerField(default=0)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_description_length', models.IntegerField(default=0)),
                ('canonical', models.URLField(blank=True, max_length=1000)),
                ('robots_meta', models.CharField(blank=True, max_length=255)),
                ('h1_text', models.TextField(blank=True)),
                ('h1_count', models.IntegerField(default=0)),
                ('h2_count', models.IntegerField(default=0)),
                ('paragraph_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('images_count', models.IntegerField(default=0)),
                ('images_without_alt', models.IntegerField(default=0)),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('seo_score', models.IntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('raw_text_excerpt', models.TextField(blank=True)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_pages', to='data_module.website')),
            ],
            options={
                'db_table': 'scraped_pages',
                'unique_together': {('website', 'url')},
            },
        ),
    ]
