# Generated by Django 6.0.2 on 2026-04-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0009_scrapedpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('technical_score', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('global_score', models.FloatField(default=0.0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.website')),
            ],
            options={
                'db_table': 'ml_scores',
            },
        ),
    ]
