# Generated by Django 6.0.2 on 2026-05-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0012_website_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISiteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_score', models.FloatField(default=0)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('global_diagnosis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_module.website')),
            ],
            options={
                'db_table': 'ai_site_score',
            },
        ),
        migrations.CreateModel(
            name='AIPageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=500)),
                ('score', models.FloatField(default=0)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.website')),
            ],
            options={
                'db_table': 'ai_page_score',
                'unique_together': {('website', 'page')},
            },
        ),
    ]
