from django.urls import path
from .views import (
    CustomLoginView,
    CustomLogoutView,
    api_login,
    api_logout,
    api_me,
    api_profile_photo,
    api_change_password,
    api_forgot_password,
    api_verify_otp,
    api_admin_list,
    api_admin_create,
    api_admin_update,
    api_admin_delete,
    jwt_test,
    api_reset_password,
    api_csrf,
    api_passkey_register_options,
    api_passkey_register_verify,
    api_passkey_login_options,
    api_passkey_login_verify,
    google_oauth_start,
    google_oauth_callback,
    github_oauth_start,
    github_oauth_callback,
    linkedin_oauth_start,
    linkedin_oauth_callback,
)

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("api/login/", api_login, name="api_login"),
    path("api/oauth/google/start/", google_oauth_start, name="google_oauth_start"),
    path("api/oauth/google/callback/", google_oauth_callback, name="google_oauth_callback"),
    path("api/oauth/github/start/", github_oauth_start, name="github_oauth_start"),
    path("api/oauth/github/callback/", github_oauth_callback, name="github_oauth_callback"),
    path("api/oauth/linkedin/start/", linkedin_oauth_start, name="linkedin_oauth_start"),
    path("api/oauth/linkedin/callback/", linkedin_oauth_callback, name="linkedin_oauth_callback"),
    path("api/logout/", api_logout, name="api_logout"),
    path("api/me/", api_me, name="api_me"),
    path("api/profile/photo/", api_profile_photo, name="api_profile_photo"),
    path("api/change-password/", api_change_password, name="api_change_password"),
    path("api/admins/", api_admin_list, name="api_admin_list"),
    path("api/admins/create/", api_admin_create, name="api_admin_create"),
    path("api/admins/<int:admin_id>/update/", api_admin_update, name="api_admin_update"),
    path("api/admins/<int:admin_id>/delete/", api_admin_delete, name="api_admin_delete"),
    path("api/jwt-test/", jwt_test, name="jwt_test"),
    path("api/forgot-password/",api_forgot_password,name="api_forgot_password",),
    path("api/verify-otp/",api_verify_otp,name="api_verify_otp",),
    path("api/reset-password/",api_reset_password,name="api_reset_password",),
    path("api/csrf/", api_csrf, name="api_csrf"),
    path("api/passkeys/register/options/",api_passkey_register_options,name="api_passkey_register_options"),
    path("api/passkeys/register/verify/",api_passkey_register_verify,name="api_passkey_register_verify"),
    path(
    "api/passkeys/login/options/",
    api_passkey_login_options,
    name="api_passkey_login_options",
),

path(
    "api/passkeys/login/verify/",
    api_passkey_login_verify,
    name="api_passkey_login_verify",
),
]
