from django.urls import path
from .views import (
    CustomLoginView,
    CustomLogoutView,
    api_login,
    api_logout,
    api_me,
    api_change_password,
    api_forgot_password,
    api_verify_otp,
    api_admin_list,
    api_admin_create,
    api_admin_update,
    api_admin_delete,
    jwt_test,
    api_reset_password,
    api_csrf,
)

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("api/login/", api_login, name="api_login"),
    path("api/logout/", api_logout, name="api_logout"),
    path("api/me/", api_me, name="api_me"),
    path("api/change-password/", api_change_password, name="api_change_password"),
    path("api/admins/", api_admin_list, name="api_admin_list"),
    path("api/admins/create/", api_admin_create, name="api_admin_create"),
    path("api/admins/<int:admin_id>/update/", api_admin_update, name="api_admin_update"),
    path("api/admins/<int:admin_id>/delete/", api_admin_delete, name="api_admin_delete"),
    path("api/jwt-test/", jwt_test, name="jwt_test"),
    path("api/forgot-password/",api_forgot_password,name="api_forgot_password",),
    path("api/jwt-test/", jwt_test, name="jwt_test"),
    path("api/verify-otp/",api_verify_otp,name="api_verify_otp",),
    path("api/reset-password/",api_reset_password,name="api_reset_password",),
    path("api/csrf/", api_csrf, name="api_csrf"),
]