# Generated by Django 6.0.2 on 2026-06-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0002_aichatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aichatmessage',
            new_name='ai_chat_mes_user_id_12ed95_idx',
            old_name='ai_module_a_user_id_0e68e8_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatmessage',
            new_name='ai_chat_mes_website_78885b_idx',
            old_name='ai_module_a_website_82e469_idx',
        ),
        migrations.RenameIndex(
            model_name='airecommendation',
            new_name='ai_recommen_website_b2f7fd_idx',
            old_name='ai_module_a_website_89df75_idx',
        ),
        migrations.RenameIndex(
            model_name='airecommendation',
            new_name='ai_recommen_user_id_9e95c5_idx',
            old_name='ai_module_a_user_id_2a1ead_idx',
        ),
        migrations.RenameIndex(
            model_name='airecommendation',
            new_name='ai_recommen_status_1454c9_idx',
            old_name='ai_module_a_status_6ced5f_idx',
        ),
    ]
