# Generated by Django 6.0.2 on 2026-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='bbb', max_length=25, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='cc', max_length=25, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09876543', max_length=8, verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
