# Generated by Django 6.0.2 on 2026-05-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.FloatField(blank=True, null=True)),
                ('bounce_rate', models.FloatField(blank=True, null=True)),
                ('pages_per_visit', models.FloatField(blank=True, null=True)),
                ('avg_visit_duration', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='similarweb', max_length=50)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_estimates', to='competitor_module.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedCompetitorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('h1', models.TextField(blank=True, null=True)),
                ('h2', models.TextField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('raw_text_excerpt', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_pages', to='competitor_module.competitor')),
            ],
            options={
                'unique_together': {('competitor', 'url')},
            },
        ),
        migrations.CreateModel(
            name='SerpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.TextField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('source', models.CharField(default='serpapi', max_length=50)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='competitor_module.competitor')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='competitor_module.keyword')),
            ],
            options={
                'unique_together': {('keyword', 'url', 'position')},
            },
        ),
    ]
